services:
  dq_static:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dq_static

    # Environment variables for database connection, etc.
    # env_file:
    #   - .env

    volumes:
      - ./app:/app

networks:
  default:
    name: dequa_nw
    external: true
